name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: octokit/rest.js  # The repository to scan.
        releases-only: true  # We know that all relevant tags have a GitHub release for them.
      id: octokit
    - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"
    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName
    - run: echo " is at version $GIT_TAG_NAME"
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: datsent/test_app:$GIT_TAG_NAME # ${{ steps.octokit.outputs.tag }}
